### ISSUE TITLE
Nemesis Sidescheme comes in sideways

### ISSUE THREAD

**Issue by ihasaflavour** [twistedsistem/OCTGN-Marvel-Champions#18]
Only tried this with Ms. Marvel. Attached a screenshot for example.
![Capture](https://user-images.githubusercontent.com/60158016/74169946-20a7da80-4bfa-11ea-9346-3aad7f7bfc3f.JPG)

**Comment by Ouroboros009** [comment]
I guess it has been fixed a long time ago since I can't reproduce that behaviour in recent updates.
