### ISSUE TITLE
Card meta-data: aspect

### ISSUE THREAD

**Issue by GeneCupstid** [twistedsistem/OCTGN-Marvel-Champions#2]
Not sure if this is the right place, but I don't see `aspect` recorded anywhere on the Marvel Champions cards.  Is it possible to add that somehow?  It would make deck building a lot easier.  If you can point me in the right direction I'd be happy to add that information somewhere.

Thanks for everything!

**Comment by GeneCupstid** [comment]
In case it wasn't obvious what I was referring to... I was expecting a column here with `aspect` name :)

![image](https://user-images.githubusercontent.com/56445225/72582957-1835db80-38aa-11ea-8710-031ea0a594f1.png)

**Comment by GeneCupstid** [comment]
By the way - I don't think you'd even need a new column.  The `owner` field would work perfectly for this, because aspects are not owned by an individual, they are owned by themselves.

**Comment by twistedsistem** [comment]
This is the perfect spot for reporting issues like this.  I will add the aspect to the card meta data on the upcoming release.  Thank you very much for pointing this out.  In the mean time you are able to build decks and import them through the URL on marvelcdb.com.  If you have any questions on that let me know.

**Comment by GeneCupstid** [comment]
Hey that's great to know about marvelcdb.com.  I'm working on a video explaining how to play the game in Octgn.  I might have a couple of other questions regarding turn steps.
