### ISSUE TITLE
Armored Rhino Suit should get damage instead of all-purpose tokens

### ISSUE THREAD

**Issue by PeteCrighton** [twistedsistem/OCTGN-Marvel-Champions#20]
It is a minor nitpick, but right now it is not possible to add damage tokens to [Armored Rhino Suit](https://marvelcdb.com/find?q=armored+rhino+suit), probably because the Attachment type defaults to all-purpose tokens. Don’t know if that’s easy to fix, and it really doesn’t make any difference for gameplay, but to be correct would be nice. :-)

**Comment by twistedsistem** [comment]
in the short term you can right click on the card and there is a menu to add any type of token that is in the game.  I will look into the Armored Rhino Suit as it is by default adding all-purpose because of the card type and I have that in the scripting.  I will look into that card.

**Comment by PeteCrighton** [comment]
That menu does not allow me to add damage tokens. Only _Add marker_ (which defaults to all-purpose) or _Add All Purpose Marker_.

**Comment by twistedsistem** [comment]
Latest update I have made it so that all the marker options are available in the right click menu to allow for the damage to be added to these cards.
