### ISSUE TITLE
Moving a Face down Side Scheme elongates the Card Back art.

### ISSUE THREAD

**Issue by ZATGamer** [twistedsistem/OCTGN-Marvel-Champions#23]
When you bring in a face down Encounter card that happens to be a Side Ways card (Side Schemes), when you move said card across the table. The card back art changes shape to a side ways card giving away what the face down card is.

Short Video Showing the bug.
https://youtu.be/4j2j818qJ7s

**Comment by ZATGamer** [comment]
![Annotation 2020-05-27 213829](https://user-images.githubusercontent.com/6774445/83096256-7184f700-a062-11ea-9aa1-812a2cb2f117.png)

**Comment by Ouroboros009** [comment]
Should be fixed now. Let me know if it's still happening with other cards.
