### ISSUE TITLE
Green Goblin: Risky Business Hostile Takeover Card side

### ISSUE THREAD

**Issue by ZATGamer** [twistedsistem/OCTGN-Marvel-Champions#24]
When playing Green Goblin: Risky Business flipping the Hostile Takeover card from 1A to 1B changes the card size, 1B is far smaller then 1A.

Video of Issue
https://youtu.be/-6GRUUfeB8I

**Comment by Ouroboros009** [comment]
Should be fixed now in yesterday update. Let me know if it's still happening with other cards.
