### ISSUE TITLE
Card Movement

### ISSUE THREAD

**Issue by GeneCupstid** [twistedsistem/OCTGN-Marvel-Champions#3]
Is it at all possible to prevent cards from moving during automations?  I like to play zoomed so I can see the cards better, and automations reset the zoom and move everything.  Not a `huge` deal or anything, but would definitely make it a bit better, visually.  Also I guess I'm just old.

I'm a developer myself, and if I can find some time, I'll peek through and see if I can pitch in and submit PRs for things if I think of them.  I know this is typically thankless work, and I appreciate it.

**Comment by twistedsistem** [comment]
The next update has a new background setup so that the villain/encounter/scheme location slots will zoom in and out as you zoom in and out.  Is this the portion you are talking about?

**Comment by GeneCupstid** [comment]
Yep, that would fix it perfectly!  Thank you!!
