### ISSUE TITLE
Groot card is flipped to wrong side at start of game and relative to hand size

### ISSUE THREAD

**Issue by jossives** [twistedsistem/OCTGN-Marvel-Champions#37]
Groot starts on Hero side with a hand size of 6 and when you flip the card to Alter Ego, the hand size goes to 5

**Comment by jossives** [comment]
Venom also comes has hand sizes reversed

**Comment by Ouroboros009** [comment]
Thanks for reporting this issue. It's not code related but come from image pack where alter-ego and hero image have been reversed. It's true for Scarlet Witch/Groot/Rocket/Star-lord/Gamora/Drax/Venom. I was kind of constant as i've done all packs in a short time.

I uploaded new o8c image packs in my drive. You can access it by going https://twistedsistem.wixsite.com/octgnmarvelchampions

Sorry for inconvenience
