### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by GeneCupstid** [twistedsistem/OCTGN-Marvel-Champions#5]
Definitely one of the most useful things that can be added, in my opinion.

Also, I just want to say that you've nailed the double-click actions.  Definitely very intuitive for each card type.  You've also nailed the add/remove for threat/damage!  

Based on 12-15 playthroughs, I've found these to be the most important actions to have a shortcut. As always, these are merely suggestions, and if nothing else possibly just a place to have discussion.

![image](https://user-images.githubusercontent.com/56445225/72705295-b6cb7200-3b20-11ea-9351-d908ceffa22d.png)

**Comment by twistedsistem** [comment]
I will say that we won't be able to put in hotkeys that are single alphabet letters.  OCTGN doesn't allow those to be hotkeys as it is preventing issues coming into play if someone were to forget to click in the chat window and starts typing a sentence.  That would trigger a lot of actions when they don't mean to.

**Comment by twistedsistem** [comment]
The UP and DOWN hotkeys today take the card type into account and adds either damage/threat/multi-purpose based on the card type.  Is the suggestion to add a left and right to be able to add Multi-Purpose to a card that would usually default to say damage?

**Comment by GeneCupstid** [comment]
> OCTGN doesn't allow those to be hotkeys as it is preventing issues coming into play if someone were to forget to click in the chat window and starts typing a sentence

Ahh, fair enough.  It's certainly not an issue to use `alt` / `ctrl` modifiers.  I don't think its a huge deal which keys they use, **just that they have one**.  Users can even re-map keys if they don't like the combination (using AutoHotKey or their gaming mouse/kbd features).

**Comment by GeneCupstid** [comment]
> The UP and DOWN hotkeys today take the card type into account and adds either damage/threat/multi-purpose based on the card type. Is the suggestion to add a left and right to be able to add Multi-Purpose to a card that would usually default to say damage?

Yes, exactly.  I think its mostly characters that have this scenario.  For example, Hawkeye.  I just recall having to access that sub-menu item specifically on multiple occasions.  

Multi-Purpose tokens can potentially end up on just about any in-play card, so having a function specifically for that would be very helpful, particularly since getting to that menu item is not convenient - adding 4 of them for Hawkeye is a huge pain.  :)
