### ISSUE TITLE
Crossbones default modular encounter are incorrect 

### ISSUE THREAD

**Issue by afonnet** [twistedsistem/OCTGN-Marvel-Champions#50]
It is a known issue that the main scheme of Crossbones states a wrong default modular set in the name of "Hydra Patrol". The booklet state that it should be "Hydra Assault" instead, and it was confirm by the game designer (source : https://hallofheroeslcg.com/official-ffg-rulings/#redskull).

Also may we had a shared.Special.Shuffle() to experimental weapon deck for Crossbone? It is not a huge deal since you can do it yourself manually but that is a nice quality of life.

**Comment by Ouroboros009** [comment]
Thanks for your feedback on issues that you encountered. I don't understand your point on adding a shuffle feature for the special deck. You can already shuffle it by right clicking on special pile.

**Comment by afonnet** [comment]
For the shuffle it's not really a feature more a quality of life. For instance, for the Thanos encounter after creating the infinity stone deck in the special pile, it is then automatically shuffle in the code. I am just asking to have the same thing for the experimental weapon deck of crossbone, since I don't believe there is a point of keeping it in order at the beginning of the game.
