### ISSUE TITLE
Missing art for Expert Guerilla Tactics side scheme

### ISSUE THREAD

**Issue by jossives** [twistedsistem/OCTGN-Marvel-Champions#57]
Expert Guerilla Tactics, which is on the backside of the Standard Guerilla Tactics side scheme, does not have card art. I updated my GMW image pack to make sure that wasn't the issue.

**Comment by Ouroboros009** [comment]
Right! It's an issue from the english image pack. You need to download and install it again.
https://drive.google.com/file/d/1jSUzmlN4xxz13r5cE5kv0tDTcap95b6T/view?usp=sharing
Thanks for the comment.
