### ISSUE TITLE
Feature request: Indicate required modulars for villains

### ISSUE THREAD

**Issue by jossives** [twistedsistem/OCTGN-Marvel-Champions#58]
I love all of the quality of life improvements y'all have been adding to OCTGN MC in recent times. With the new villain loading sequence, I notice that required modulars are automatically loaded (eg Taskmaster has Hydra Patrol), but this isn't communicated anywhere so the first time I tried to play Taskmaster, I had two copies of Hydra Patrol because I had also added Hydra Patrol during the loading sequence.

**Comment by Ouroboros009** [comment]
Thanks for your feedback. It's true there is a lack of communication about required modulars automatically loaded. I'll think about it for future update but not in the next one.

**Comment by Ouroboros009** [comment]
Will also be answered in the next update.
