### ISSUE TITLE
Feature request: optional alphabetical ordering for modular sets when loading

### ISSUE THREAD

**Issue by jossives** [twistedsistem/OCTGN-Marvel-Champions#59]
The current order of the modular sets when loading the scenario is grouped by release set, but a quality of life feature could be to optionally sort them alphabetically.

**Comment by Ouroboros009** [comment]
Should not be too hard to make such a feature available. I'll look upon it.
Twistedsistem not working on OCTGN MC module anymore for almost 2 years.
For tracking purpose, could you post future request to https://github.com/Ouroboros009/OCTGN-Marvel-Champions instead ?
Thanks! And Mutant Genesis soon (next week) in OCTGN by the way!

**Comment by Ouroboros009** [comment]
Hello! Almost a year since you opened this request but it will be answered in the next update with NeXt Evolution.
