### ISSUE TITLE
Hawkeye Counters

### ISSUE THREAD

**Issue by ihasaflavour** [twistedsistem/OCTGN-Marvel-Champions#6]
Would be nice if there was a way he came into play with his 4 counters. AND/OR, a quick way to remove them.

**Comment by twistedsistem** [comment]
Can look at card specifics like this. Have you been using the arrow up and arrow down hotkeys to quickly add and remove the markers?  If so are you looking for an even faster way?

**Comment by ihasaflavour** [comment]
I have not. The up/down I use for damage, perhaps I'm doing it wrong?
The issue is when I'm tracking damage AND counters for his arrows.

I'll try to keep my mind and eye open for similar cards. A few come to mind right away (anything that enters play with counters):

- Web-shooter
- Tac Team
- Med Team
- Surveillance Team
- Enhanced Awareness
- Energy Barrier
- Enhanced Reflexes

**Comment by GeneCupstid** [comment]
I've also [requested ](https://github.com/twistedsistem/OCTGN-Marvel-Champions/issues/5) keybindings (`LEFT` and `RIGHT`) for "Remove" / "Add" Multi-Purpose Token.  I think @twistedsistem is open to implementing that in the next update.  

In fact, Hawkeye was my primary use case for that.

**Comment by twistedsistem** [comment]
I think short term having an extra way to add Multi-Purpose Tokens like the LEFT or RIGHT hotkeys will be a good idea.  Long term I agree that we should find all the cards that have a constant like Hawkeye and implement them being played with the correct amount of counters on them.
