### ISSUE TITLE
Editable Shortcut keys

### ISSUE THREAD

**Issue by ihasaflavour** [twistedsistem/OCTGN-Marvel-Champions#9]
Message from Discord:
ihasaflavourLast Tuesday at 8:36 PM
Is there anyway to rebind keys, or create our own shortcuts?
Also, when you right click>advance scheme for ultron, 1 goes to stage 3, then 3 goes to 2 :slight_smile:
 
twistedsistemLast Tuesday at 9:12 PM
i will add the advance to the list....you can't change the shortcuts on your own unless you change it in the build definition and make your own package
having said that go ahead and get a list of ones that you would like and we can look at adding it in as a secondary hotkey or even as the primary one

As for where this idea came from, it was from flipping a card over. I'd love to have either 'F' clip the card, or even the ability to map shortcuts to mouse buttons.

**Comment by twistedsistem** [comment]
We are unable to set keyboard shortcuts to alphabet keys as that could cause issues if a users forgets to click int he chat box and wants to start typing a message causing them to accidentally trigger some actions.
